# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: demo
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      initialize-on-context-refresh: true
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_monitor
    username: postgres
    password: 24082001
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        entitymanager:
          factory:
            interface: jakarta.persistence.EntityManagerFactory
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  jackson:
    serialization:
      indent-output: true
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,mappings
  endpoint:
    health:
      show-components: always
      show-details: always
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  show-actuator: true
info:
  app:
    name: Currency Service
    version: 1.0.0
    description: 'This service manages currency, currency pairs and their exchange
      rates.                        '
